### ISSUE TITLE
404 for Mermaid JS from UNPKG

### ISSUE THREAD

**Issue by Pezmc** [KevinGimbel/eleventy-plugin-mermaid#2]
https://unpkg.com/mermaid/dist/mermaid.min.js is expanding to https://unpkg.com/mermaid@10.0.0/dist/mermaid.min.js, which 404's

Related to the V10 upgrade of Mermaid which includes https://github.com/mermaid-js/mermaid/issues/3590

It looks like the new URL is https://unpkg.com/mermaid/dist/mermaid.esm.min.mjs which is the ESModule version of mermaid

Edit: Alternatively, swapping to https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js fixes the issue since `jsdelivr` has bee configured to still serve the old file

**Comment by KevinGimbel** [comment]
Oh no :<

That's really unfortunate. I'll release a fix for it, thanks for bringing this to my attention!

**Comment by Pezmc** [comment]
Heads up that you'll need to set the module flag if swapping to the esm version

**Comment by KevinGimbel** [comment]
It's fixed and a new version 2.0.0 is released.

**Comment by Pezmc** [comment]
Amazing, thank you for such a prompt reply, really appreciate it, will update to 2.0.0 shortly.
